version: '3.4'

services:
  ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
    depends_on:
        - microserprimos
        - microserpersona

  microserprimos:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4000:80"

  microserpersona:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

